### PR TITLE
Fix edit course validation

### PR DESCRIPTION
**Pull request by joel-foo**
- Added tests for edit course validation (for functions added in previous PR).
- Throws exception if trying to delete/change a course that does not exist.

### CODE REVIEW

**Comment by joel-foo** [comment]
closes #108

**Review by chewjh1234 — CHANGES_REQUESTED** [review]
There seems to be a bug. It may have been there since the 'Emergency` tag was introduced. 

I am not able to edit the courses of Persons with an `Emergency` tag when my address book already has 2 Emergency contacts. 
The error message "Cannot add more than two contacts with the 'emergency' tag" is returned even if the courses to be updated are valid. 

I suspect that it is because we are creating the new updated person (also with an emergency tag) before we delete the original person. 

I'm currently looking to it. Will file a new issue if that is indeed the case. 
Are you all able to reproduce the bug? 

Screenshot 2023-10-22 at 6 03 08 PM

**Review by chewjh1234 — APPROVED** [review]
I have separately filed another issue to address the bug (which has nothing to do with the code here) in my previous review (#110). 

Your code works perfectly and the correct error messages shown when the user attempts to delete a non-existent course :D

LGTM! Thank you!

**Comment by joel-foo** [comment]
Hi, I managed to reproduce the same bug. Thank you for spotting this!

**Comment by joel-foo** [comment]
@tanteckfang hi, I have helped you to resolve this issue. 

please try out and see if it works now!

**Comment by joel-foo** [comment]
closes #110

**Pull request merged**
