### PR TITLE
Remove profile picture from Ui Mockup

### LINKED ISSUE #7: Update project website - ReadMe
Screenshot 2023-09-22 at 10 47 28 PM

### PR DESCRIPTION
**Pull request by Carlintyj**
Fixes #7

### CODE REVIEW

**Review by joel-foo — DISMISSED** [review]
LGTM

**Review by joel-foo — CHANGES_REQUESTED** [review]
hi, need to resolve the merge conflict locally

**Comment by Carlintyj** [comment]
Hi, I have resolved the conflict.

**Review by joel-foo — APPROVED** [review]
LGTM

**Pull request merged**
